name: flutter_extend
description: "Simple, Efficient Flutter Extensions! Supercharge your Flutter development with a collection of easy-to-use, lightweight, and practical extension methods."
version: 0.3.0
homepage: https://starrycodes.mintlify.app/flutter_extend/introduction

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  intl: ^0.20.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

